### ISSUE TITLE
WSO2 Analytics with ansible in a distributed environment

### ISSUE THREAD

**Issue by ericomtx** [wso2/ansible-apim#107]
Please

I'm currently working in a distributed API Manager and Analytics environment to be set through ansible scripts

I need to run analytics balanced through 2 IPs

In my project structure I have the following:
ansible-apim/roles/apim-analytics-worker/templates/carbon-home/conf/dashboard/deployment.yaml.j2

and in this yaml the following content:
baseUrl: https://localhost:9643

When I try to connect in Analytics :
https://<my-host-ip>:9643/analytics-dashboard

It tries to redirect it to localhost

I have read the documentation:

https://apim.docs.wso2.com/en/3.0.0/learn/analytics/configuring-apim-analytics/#step-5-configure-apim-idp-client

How can I change the baseUrl so that when I ran the ansible script it reflects properly in both distributed environment IPs ?

Thks!!

**Comment by Savidude** [comment]
It seems like you are applying configurations for the Dashboard in the Worker role. You can find the Dashboard role configurations in `ansible-apim/roles/**apim-analytics-dashboard**/templates/carbon-home/conf/dashboard/deployment.yaml.j2`

Once the dashboard configurations are made, you can add the environment to the inventory file and and run the playbook scripts.
