### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by daz96050** [wso2/ansible-apim#109]
**Description:**
apim-gateway.yml file missing from /dev/group_vars
File is referenced for [Deployment Pattern 2](https://github.com/wso2/ansible-apim/blob/master/docs/Pattern_2.md) but is not 
 provided in the /dev directory

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VimukthiPerera** [comment]
Fixed with https://github.com/wso2/ansible-apim/pull/123
