### ISSUE TITLE
[3.x] Patterns point to 2.6.0 documents for configuration

### ISSUE THREAD

**Issue by lahirus** [wso2/ansible-apim#111]
**Description:**

Navigate to carbon-home of the apim-analytics-worker role. All the files required to deploy the API Manager analytics are here. Follow the instructions in the following files to modify the files.

**Configure Analytics
Minimum HA deployment**

Above links are pointing to old versions.
[1] https://github.com/wso2/ansible-apim/blob/3.1.x/docs/Pattern_2.md

**Affected Product Version:**
3.1.x branch.

**Comment by VimukthiPerera** [comment]
The documentation for 3.2.x is also still pointing to 2.6.x
