### ISSUE TITLE
APIM Gateway Profile is not deploying 

### ISSUE THREAD

**Issue by ahsancse** [wso2/ansible-apim#124]
**Description:**
APIM Gateway Profile is not deploying . When  analyse the carbon logs its noticed that this is a toml parser issue in deployment.toml.j2 template of gateway role due to some duplicate tags

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.2 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run ansible-playbook  with gateway profile information in the site.yml

**Related Issues:**

**Comment by VimukthiPerera** [comment]
Fixed with https://github.com/wso2/ansible-apim/pull/125
