### ISSUE TITLE
Spell error in the ansible-apim/files/security/ in both files and all profiles

### ISSUE THREAD

**Issue by chamindi-a** [wso2/ansible-apim#169]
**Description:**
Observed a spelling error in the word 'truststore' in the above-mentioned files.

**Steps to reproduce:**
go to ansible-apim/files/security/ location and open the two files there 
Search for word 'trsustrores'
      Wrong spelling needs correction[ Same error persist in both file in the mentioned directory]

**Comment by bbaassssiiee** [comment]
Issue can be closed.
